baseURL = "/"
title = "Francois Gerber"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "I'm Francois Gerber"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Web Applications and Mobile Software Developer" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Passionate about coding, reading, cooking, gardening, and hiking. Let's explore technology and storytelling together! 💻📚✍️🌱🌄"

    # The name to display in the copyright section in the footer
    copyrightname = "Francois Gerber"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "https://francoisgerber.github.io/FrancoisGerber/"

    # Show the "built on Hugo" disclaimer
    showhugo = false

    # Urls for social networks
    twitter = "https://x.com/Francoisantonie"
    linkedin = "https://www.linkedin.com/in/francois-antonie-gerber/"
    github = "https://github.com/FrancoisGerber"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "Francois Gerber"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https://www.francoisgerber.co.za/"

    # Text to go before copyright information
    prefix = ""

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"

